### ISSUE TITLE
Missing IQmathLib.h

### ISSUE THREAD

**Issue by sburdka** [lehn85/PMSM-sensored-STM32F103C8T6#1]
I didn't found IQmathLib.h source file in the project folder.

**Comment by lehn85** [comment]
I used IQmath from Texas Instrument.
https://www.ti.com/tool/SW-TM4C-IQMATH?keyMatch=IQMATH&tisearch=Search-EN-everything&usecase=GPN

**Comment by suyog44** [comment]
I have attached IQmathLib.h and IQmathLib.lib files in the source project. I think library didn't attached or compatible with stm32 platform. following error is coming.

PMSM\PMSM.axf: Error: L6218E: Undefined symbol _IQ20div (referred from currentregulator.o).
PMSM\PMSM.axf: Error: L6218E: Undefined symbol _IQ24div (referred from currentregulator.o).
PMSM\PMSM.axf: Error: L6218E: Undefined symbol _IQ24sqrt (referred from currentregulator.o).
PMSM\PMSM.axf: Error: L6218E: Undefined symbol __IQmpy (referred from currentregulator.o).
PMSM\PMSM.axf: Error: L6218E: Undefined symbol _IQdiv2 (referred from libfoc.o).
PMSM\PMSM.axf: Error: L6218E: Undefined symbol _IQmpy2 (referred from libfoc.o).
PMSM\PMSM.axf: Error: L6218E: Undefined symbol _IQ24cosPU (referred from qep.o).
PMSM\PMSM.axf: Error: L6218E: Undefined symbol _IQ24sinPU (referred from qep.o).
PMSM\PMSM.axf: Error: L6218E: Undefined symbol _IQ24atan2PU (referred from main_model.o).
PMSM\PMSM.axf: Error: L6218E: Undefined symbol __IQsat (referred from main_model.o).
